### ISSUE TITLE
More Details?

### ISSUE THREAD

**Issue by alanpuccinelli** [waltmoorhouse/OctoPrint-Filamentstorage#1]
Found this through your Octo plugin. This is awesome and parallels the development of my next gen dehumidification kit for RepBox! Nice work! Do you have images / more details somewhere? Let me know if you're interested in possibly collaborating on development. apuccinelli at repkord dot com

**Comment by waltmoorhouse** [comment]
Will have images for the build when I get the parts. Will send you an email re: collaboration.
