### ISSUE TITLE
Err: NO SERIAL PORTS FOUND!

### ISSUE THREAD

**Issue by SebiKDIY** [waltmoorhouse/OctoPrint-Filamentstorage#2]
Hello waltmoorhouse,

thanks for your work setting up these plug-in for octoprint. I'm not very experienced with linux, however I tried to set up an arduino with a temperature sensor and connected it to the raspberry pi via USB-cable.  The raspberry pi is detecting the arduino uno as ttyUSB0 and by running a small python script I found out that the arduino is sending data in the demanded format. Sadly the plug-in only throws the error massage no Serial Ports found! 
Can you help me any further?

**Comment by waltmoorhouse** [comment]
@SIslandRU please check this branch and see if it helps: https://github.com/waltmoorhouse/OctoPrint-Filamentstorage/tree/issue_2 

If that one doesn't work, please run the following command and send me the output.

sudo ls /dev/*USB* && sudo ls /dev/*usb*
